-- MySQL Script generated by MySQL Workbench
-- Fri Nov 27 00:47:16 2020
-- Model: tables-online-testing    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
--
--
--

-- -----------------------------------------------------
-- Schema new_schema1
--
--
--
--
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`test` (
  `id` INT NOT NULL,
  `test_name` VARCHAR(255) NULL DEFAULT NULL,
  `test_theme` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`questions` (
  `id` INT NOT NULL,
  `text` VARCHAR(255) NULL DEFAULT NULL,
  `test_id` INT NOT NULL,
  PRIMARY KEY (`id`, `test_id`),
  INDEX `fk_questions_test1_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `new_schema1`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`possible_answer_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`possible_answer_question` (
  `id` INT NOT NULL,
  `text_answer` VARCHAR(255) NULL DEFAULT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_possible_answer_question_questions2_idx` (`questions_id` ASC) VISIBLE,
  CONSTRAINT `fk_possible_answer_question_questions2`
    FOREIGN KEY (`questions_id`)
    REFERENCES `new_schema1`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`answer_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`answer_test` (
  `id` INT NOT NULL,
  `id_user` INT NULL DEFAULT NULL,
  `result` INT NOT NULL,
  `test_id` INT NOT NULL,
  PRIMARY KEY (`id`, `test_id`),
  INDEX `fk_answer_test_test1_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_test_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `new_schema1`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`answer_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`answer_question` (
  `id` INT NOT NULL,
  `id_user` INT NULL DEFAULT NULL,
  `answer_to_the_question` VARCHAR(255) NOT NULL,
  `correct_answer` VARCHAR(45) NULL DEFAULT NULL,
  `questions_id` INT NOT NULL,
  `possible_answer_question_id` INT NOT NULL,
  `answer_test_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answer_question_questions1_idx` (`questions_id` ASC) VISIBLE,
  INDEX `fk_answer_question_possible_answer_question1_idx` (`possible_answer_question_id` ASC) VISIBLE,
  INDEX `fk_answer_question_answer_test2_idx` (`answer_test_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question_possible_answer_question1`
    FOREIGN KEY (`possible_answer_question_id`)
    REFERENCES `new_schema1`.`possible_answer_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_question_answer_test2`
    FOREIGN KEY (`answer_test_id`)
    REFERENCES `new_schema1`.`answer_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`user_has_answer_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`user_has_answer_test` (
  `user_id` INT NOT NULL,
  `user_test_id` INT NOT NULL,
  `answer_id` INT NOT NULL,
  `answer_test_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_test_id`, `answer_id`, `answer_test_id`),
  INDEX `fk_user_has_answer_test_answer_test1_idx` (`answer_id` ASC, `answer_test_id` ASC) VISIBLE,
  INDEX `fk_user_has_answer_test_user1_idx` (`user_id` ASC, `user_test_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_answer_test_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `new_schema1`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_answer_test_answer_test1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `new_schema1`.`answer_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`user_has_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`user_has_test` (
  `user_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `test_id`),
  INDEX `fk_user_has_test_test1_idx` (`test_id` ASC) VISIBLE,
  INDEX `fk_user_has_test_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_test_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `new_schema1`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_test_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `new_schema1`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
