-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 21:52:44 2020
-- Model: tables-online-testing    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_testing_db
-- -----------------------------------------------------
--
--
--

-- -----------------------------------------------------
-- Schema online_testing_db
--
--
--
--
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_testing_db` ;
USE `online_testing_db` ;

-- -----------------------------------------------------
-- Table `online_testing_db`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_testing_db`.`test` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `theme` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_testing_db`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_testing_db`.`questions` (
  `id` INT NOT NULL,
  `text` VARCHAR(255) NULL DEFAULT NULL,
  `test_id` INT NOT NULL,
  PRIMARY KEY (`id`, `test_id`),
  INDEX `fk_questions_test1_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `online_testing_db`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_testing_db`.`possible_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_testing_db`.`possible_answer` (
  `id` INT NOT NULL,
  `text_answer` VARCHAR(255) NULL DEFAULT NULL,
  `correct_answer` TINYINT(1) NULL DEFAULT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_possible_answer_question_questions2_idx` (`questions_id` ASC) VISIBLE,
  CONSTRAINT `fk_possible_answer_question_questions2`
    FOREIGN KEY (`questions_id`)
    REFERENCES `online_testing_db`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_testing_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_testing_db`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_testing_db`.`answer_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_testing_db`.`answer_test` (
  `id` INT NOT NULL,
  `result` INT NOT NULL,
  `test_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `test_id`, `user_id`),
  INDEX `fk_answer_test_test1_idx` (`test_id` ASC) VISIBLE,
  INDEX `fk_answer_test_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_test_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `online_testing_db`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_test_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_testing_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_testing_db`.`answer_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_testing_db`.`answer_question` (
  `id` INT NOT NULL,
  `possible_answer_question_id` INT NOT NULL,
  `answer_test_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answer_question_possible_answer_question1_idx` (`possible_answer_question_id` ASC) VISIBLE,
  INDEX `fk_answer_question_answer_test2_idx` (`answer_test_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question_possible_answer_question1`
    FOREIGN KEY (`possible_answer_question_id`)
    REFERENCES `online_testing_db`.`possible_answer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_question_answer_test2`
    FOREIGN KEY (`answer_test_id`)
    REFERENCES `online_testing_db`.`answer_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_testing_db`.`user_tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_testing_db`.`user_tests` (
  `user_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `test_id`),
  INDEX `fk_user_has_test_test1_idx` (`test_id` ASC) VISIBLE,
  INDEX `fk_user_has_test_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_test_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_testing_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_test_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `online_testing_db`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
